[package]
name = "dominator_helpers"
description = "helpers for Dominator"
version = "0.2.2"
authors = ["David Komer <david.komer@gmail.com>"]
edition = "2018"
documentation = "https://docs.rs/dominator-helpers"
homepage = "https://github.com/dakom/dominator-helpers"
repository = "https://github.com/dakom/dominator-helpers"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["javascript", "dom", "reactive", "signal", "frp"]
categories = ["gui", "web-programming", "wasm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
ts_test = []
